# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 20:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('medula', models.CharField(max_length=1)),
                ('legenda', models.TextField()),
                ('id_doacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hemocentro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('horario', models.DateTimeField(blank=True, null=True)),
                ('cidade', models.CharField(max_length=40)),
                ('estado', models.CharField(max_length=15)),
                ('rua', models.CharField(max_length=50)),
                ('numero', models.CharField(max_length=6)),
                ('bairro', models.CharField(max_length=30)),
                ('complemento', models.CharField(max_length=15)),
                ('cep', models.IntegerField()),
                ('id_hemocentro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requisicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('data', models.DateField()),
                ('tipo_sangue', models.CharField(max_length=2)),
                ('fator_rh', models.CharField(max_length=3)),
                ('id_requisicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fathor_rh', models.CharField(max_length=3)),
                ('senha', models.CharField(max_length=30)),
                ('nome', models.CharField(max_length=60)),
                ('data_nasc', models.DateField()),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
                ('email', models.EmailField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('tipo_sangue', models.CharField(max_length=2)),
                ('id_login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
